# Zola build workflow.

# Setting it up:
#   Adjust the variables below, under env.
#
#   It is a general limitation of gh-actions that they cannot make the very first
#   deploy to gh-pages.  It will seem to work, but not appear on the CDN to be
#   online.  You need to go to settings and set the gh-pages branch, then future
#   deploys will work.  See
#   https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token

name: Build and deploy website preview

env:
  ZOLA_VERSION: "0.18.0"
  TARGET_BRANCH: "gh-pages"
  CNAME: "nordic-rse.org"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # if this build is a PR build and the PR is NOT from a fork
    if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install zola
      run: |
        set -x
        wget -O - \
           "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin

    - name: Generate HTML
      run: zola build --base-url "https://nordic-rse.org/previews/PR${{ github.event.number }}"

    - name: Deploy website
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
          TARGET_FOLDER: "previews/PR${{ github.event.number }}" # The website preview is going to be stored in the previews subfolder
